// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZD5uDHfJ7QTtvfWBQp3jzh5pqyUS038',
    appId: '1:901619753691:web:a29e2f329de8180fa862fe',
    messagingSenderId: '901619753691',
    projectId: 'flutter-course-d99e0',
    authDomain: 'flutter-course-d99e0.firebaseapp.com',
    storageBucket: 'flutter-course-d99e0.appspot.com',
    measurementId: 'G-VGZR32LX1T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEN-f4f2gmsKvqyhvYtZT1rHWIR1M2mdQ',
    appId: '1:901619753691:android:b294b336cc2dce89a862fe',
    messagingSenderId: '901619753691',
    projectId: 'flutter-course-d99e0',
    storageBucket: 'flutter-course-d99e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNUNM43yeR9VRoqFavIxUVtvHUFPrlO4',
    appId: '1:901619753691:ios:4e0f4b0ad85bbbf4a862fe',
    messagingSenderId: '901619753691',
    projectId: 'flutter-course-d99e0',
    storageBucket: 'flutter-course-d99e0.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNUNM43yeR9VRoqFavIxUVtvHUFPrlO4',
    appId: '1:901619753691:ios:4e0f4b0ad85bbbf4a862fe',
    messagingSenderId: '901619753691',
    projectId: 'flutter-course-d99e0',
    storageBucket: 'flutter-course-d99e0.appspot.com',
    iosBundleId: 'com.example.flutterCourse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeZD5uDHfJ7QTtvfWBQp3jzh5pqyUS038',
    appId: '1:901619753691:web:a4b9cb8c25ceef38a862fe',
    messagingSenderId: '901619753691',
    projectId: 'flutter-course-d99e0',
    authDomain: 'flutter-course-d99e0.firebaseapp.com',
    storageBucket: 'flutter-course-d99e0.appspot.com',
    measurementId: 'G-ML1VWY669Y',
  );
}
